baseURL = 'https://www.brad.fi/'
languageCode = 'en-us'
title = 'Brad Baker - brad.fi'
theme = "ascii-theme"
publishDir = '/var/www/brad-fi/html'
copyright = "Â©"
contentDir = 'content'

[permalinks]
'/' = '/:filename/'

[frontmatter]
publishDate = ['publishDate', 'date']

# Header
[menu]
  [[menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "/resume/"
        weight = 1 

  [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 2 

  [[menu.main]]
        identifier = "colophon"
        name = "Colophon"
        url = "/colophon/"
        weight = 3
